var annotated_dup =
[
    [ "trajopt", null, [
      [ "AngularVelocityMaxMagnitudeConstraint", "classtrajopt_1_1AngularVelocityMaxMagnitudeConstraint.html", "classtrajopt_1_1AngularVelocityMaxMagnitudeConstraint" ],
      [ "DifferentialDrivetrain", "structtrajopt_1_1DifferentialDrivetrain.html", "structtrajopt_1_1DifferentialDrivetrain" ],
      [ "DifferentialSolution", "structtrajopt_1_1DifferentialSolution.html", "structtrajopt_1_1DifferentialSolution" ],
      [ "DifferentialTrajectory", "classtrajopt_1_1DifferentialTrajectory.html", "classtrajopt_1_1DifferentialTrajectory" ],
      [ "DifferentialTrajectoryGenerator", "classtrajopt_1_1DifferentialTrajectoryGenerator.html", "classtrajopt_1_1DifferentialTrajectoryGenerator" ],
      [ "DifferentialTrajectorySample", "classtrajopt_1_1DifferentialTrajectorySample.html", "classtrajopt_1_1DifferentialTrajectorySample" ],
      [ "KeepOutRegion", "structtrajopt_1_1KeepOutRegion.html", "structtrajopt_1_1KeepOutRegion" ],
      [ "LaneConstraint", "classtrajopt_1_1LaneConstraint.html", "classtrajopt_1_1LaneConstraint" ],
      [ "LinearAccelerationMaxMagnitudeConstraint", "classtrajopt_1_1LinearAccelerationMaxMagnitudeConstraint.html", "classtrajopt_1_1LinearAccelerationMaxMagnitudeConstraint" ],
      [ "LinearVelocityDirectionConstraint", "classtrajopt_1_1LinearVelocityDirectionConstraint.html", "classtrajopt_1_1LinearVelocityDirectionConstraint" ],
      [ "LinearVelocityMaxMagnitudeConstraint", "classtrajopt_1_1LinearVelocityMaxMagnitudeConstraint.html", "classtrajopt_1_1LinearVelocityMaxMagnitudeConstraint" ],
      [ "LinePointConstraint", "classtrajopt_1_1LinePointConstraint.html", "classtrajopt_1_1LinePointConstraint" ],
      [ "Path", "structtrajopt_1_1Path.html", "structtrajopt_1_1Path" ],
      [ "PathBuilder", "classtrajopt_1_1PathBuilder.html", "classtrajopt_1_1PathBuilder" ],
      [ "PointAtConstraint", "classtrajopt_1_1PointAtConstraint.html", "classtrajopt_1_1PointAtConstraint" ],
      [ "PointLineConstraint", "classtrajopt_1_1PointLineConstraint.html", "classtrajopt_1_1PointLineConstraint" ],
      [ "PointLineRegionConstraint", "classtrajopt_1_1PointLineRegionConstraint.html", "classtrajopt_1_1PointLineRegionConstraint" ],
      [ "PointPointMaxConstraint", "classtrajopt_1_1PointPointMaxConstraint.html", "classtrajopt_1_1PointPointMaxConstraint" ],
      [ "PointPointMinConstraint", "classtrajopt_1_1PointPointMinConstraint.html", "classtrajopt_1_1PointPointMinConstraint" ],
      [ "Pose2", "classtrajopt_1_1Pose2.html", "classtrajopt_1_1Pose2" ],
      [ "PoseEqualityConstraint", "classtrajopt_1_1PoseEqualityConstraint.html", "classtrajopt_1_1PoseEqualityConstraint" ],
      [ "Rotation2", "classtrajopt_1_1Rotation2.html", "classtrajopt_1_1Rotation2" ],
      [ "SwerveDrivetrain", "structtrajopt_1_1SwerveDrivetrain.html", "structtrajopt_1_1SwerveDrivetrain" ],
      [ "SwerveSolution", "structtrajopt_1_1SwerveSolution.html", "structtrajopt_1_1SwerveSolution" ],
      [ "SwerveTrajectory", "classtrajopt_1_1SwerveTrajectory.html", "classtrajopt_1_1SwerveTrajectory" ],
      [ "SwerveTrajectoryGenerator", "classtrajopt_1_1SwerveTrajectoryGenerator.html", "classtrajopt_1_1SwerveTrajectoryGenerator" ],
      [ "SwerveTrajectorySample", "classtrajopt_1_1SwerveTrajectorySample.html", "classtrajopt_1_1SwerveTrajectorySample" ],
      [ "Translation2", "classtrajopt_1_1Translation2.html", "classtrajopt_1_1Translation2" ],
      [ "TranslationEqualityConstraint", "classtrajopt_1_1TranslationEqualityConstraint.html", "classtrajopt_1_1TranslationEqualityConstraint" ],
      [ "Waypoint", "structtrajopt_1_1Waypoint.html", "structtrajopt_1_1Waypoint" ]
    ] ]
];