// Copyright (c) Choreo contributors

// Auto-generated by update_field_dimensions.py
package choreo.util;

class FieldDimensions {
  static final double FIELD_LENGTH = 16.7215312;
  static final double FIELD_WIDTH = 8.0264;
}
