// Copyright (c) Choreo contributors

// Auto-generated by update_field_dimensions.py
package choreo.util;

class FieldDimensions {
  static final double FIELD_LENGTH = 16.541;
  static final double FIELD_WIDTH = 8.0692;
}
