// Copyright (c) Choreo contributors

// Auto-generated by update_traj_schema.py

package choreo.util;

/** Internal autogenerated class for storing the current trajectory schema version. */
public class TrajSchemaVersion {
  /** The current trajectory schema version. */
  public static final int TRAJ_SCHEMA_VERSION = 1;

  /** Utility class. */
  private TrajSchemaVersion() {}
}
