import { Trajectory } from "../document/schema/DocumentTypes";

export const TRAJ_NAMES_FILENAME = "ChoreoTrajNames";

export function genTrajNamesFile(
  trajectories: Trajectory[],
  packageName: string
): string {
  const content: string[] = [];
  const usedVarNames: Record<string, number> = {};
  content.push(`package ${packageName};`);
  content.push(`
/**
 * A class containing the names of all trajectories created in the Choreo GUI.
 * This allows for references to non-existent or deleted trajectories
 * to be caught at compile time. DO NOT MODIFY THIS FILE YOURSELF!
 * It is automatically generated by Choreo.
 */
public final class ${TRAJ_NAMES_FILENAME} {`);
  for (const traj of trajectories) {
    if (traj.trajectory.samples.length === 0) {
      continue;
    }
    let varName = sanitizeTrajName(traj.name);
    const dupeCount = usedVarNames[varName];
    if (dupeCount > 0) {
      varName += `_${dupeCount}`;
      usedVarNames[varName] = dupeCount + 1;
    } else {
      usedVarNames[varName] = 1;
    }
    content.push(`    public static final String ${varName} = "${traj.name}";`);
  }
  content.push("");
  content.push(`    private ${TRAJ_NAMES_FILENAME}() {}`);
  content.push("}");
  return content.join("\n");
}

function sanitizeTrajName(trajName: string): string {
  let newName = trajName;
  for (let i = 0; i < newName.length; i++) {
    const char = newName.charAt(i);
    if (char !== " ") continue;
    newName =
      newName.slice(0, i) +
      newName.charAt(i + 1).toUpperCase() +
      newName.slice(i + 2);
  }
  newName = newName.replaceAll(/[^\w|^$]/g, "");
  if (newName.charAt(0).match(/[0-9]/)) {
    newName = "_" + newName;
  }
  return newName;
}
