// Copyright (c) Choreo contributors

// Auto-generated by update_field_dimensions.py

#pragma once

#include "wpi/units/length.hpp"

namespace choreo::util {
using namespace wpi;
static constexpr units::meter_t fieldLength = 16.541_m;
static constexpr units::meter_t fieldWidth = 8.0692_m;
}  // namespace choreo::util
