// Copyright (c) Choreo contributors

// Auto-generated by update_traj_schema.py

#pragma once

#include <stdint.h>

namespace choreo {

inline constexpr uint32_t kTrajSchemaVersion = 3;

}  // namespace choreo
