// Copyright (c) Choreo contributors

// Auto-generated by update_traj_schema.py

#pragma once

#include <stdint.h>

namespace choreo {

[[deprecated("Use kTrajSchemaVersion.")]]
inline constexpr uint32_t kTrajSpecVersion = 2;
inline constexpr uint32_t kTrajSchemaVersion = 2;

}  // namespace choreo
