name: Docs

on: [pull_request, push]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Run JavaDoc
        run: |
          cd choreolib
          ./gradlew javadoc

      - name: Copy API docs
        run: ./make-docs.sh

      - run: mkdocs build --dirty
        if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/v')

      - run: mkdocs gh-deploy --dirty --force
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
