name: Docs

on: [pull_request, push]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material

      - name: Create Doxygen build directory
        run: mkdir -p choreolib/build/docs/cpp

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@edge
        with:
          working-directory: "choreolib"
          doxyfile-path: "docs/Doxyfile"

      - name: Run JavaDoc
        run: |
          cd choreolib
          ./gradlew javadoc

      - name: Copy API docs
        run: ./make-docs.sh

      - run: mkdocs build --dirty
        if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/v')

      - run: mkdocs gh-deploy --dirty --force
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
