name: Choreo -> ChoreoLib Integration Test

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Generate trajectories for integration test"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Install Linux dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y \
            build-essential \
            curl \
            file \
            libayatana-appindicator3-dev \
            libgtk-3-dev \
            librsvg2-dev \
            libssl-dev \
            libwebkit2gtk-4.0-dev \
            wget

      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.5
      - name: Cargo test Generate latest
        run: cargo test -- integration_tests::generate::generate::generate_latest
      - uses: actions/upload-artifact@v4
        with:
          name: swerve.traj
          path: ./src-core/test-tmp-latest/swerve/swerve.traj
      - uses: actions/upload-artifact@v4
        with:
          name: differential.traj
          path: ./src-core/test-tmp-latest/differential/differential.traj
